### ISSUE TITLE
Always waiting "Obtaining bundled SAN certificate"

### ISSUE THREAD

**Issue by brilliantwf** [pahud/c9-ide#2]
Unable start the C9 server , always display  "Activating privacy features... 2019/02/02 14:00:01 [INFO] [code.XXX.xyz] acme: Obtaining bundled SAN certificate" in Log(make logtail) after make run .
any workaround?
ENV:
AWS Linux2 AMI,R53->ALB->EC2

**Comment by pahud** [comment]
Hey, you can't use ALB in this project. Please remove ALB and try again.

**Comment by brilliantwf** [comment]
Thanks ,It's worked!
