### ISSUE TITLE
Couldn't get ecr images 

### ISSUE THREAD

**Issue by iceflow** [pahud/c9-ide#5]
[root@ip-172-31-32-14 c9-ide]# $(aws ecr get-login --region cn-northwest-1 --no-include-email) 
WARNING! Using --password via the CLI is insecure. Use --password-stdin.
WARNING! Your password will be stored unencrypted in /root/.docker/config.json.
Configure a credential helper to remove this warning. See
https://docs.docker.com/engine/reference/commandline/login/#credentials-store

Login Succeeded
[root@ip-172-31-32-14 c9-ide]# USE_ECR=1 DOMAIN=labs-dev.armor5.cn EMAIL=chenlt78@qq.com MYUSERNAME=xxx MYPASSWORD=xxx make run
Unable to find image '937788672844.dkr.ecr.cn-northwest-1.amazonaws.com.cn/c9-ide:amazonlinux-full' locally
docker: Error response from daemon: Get https://937788672844.dkr.ecr.cn-northwest-1.amazonaws.com.cn/v2/c9-ide/manifests/amazonlinux-full: no basic auth credentials.
See 'docker run --help'.
make: *** [run] Error 125
[root@ip-172-31-32-14 c9-ide]# 

The test EC2 in Ningxia region already has attached role with administrator privilege.
I don't know if there is a good to to share ECR images publicly except cross account assume role.

**Comment by pahud** [comment]
Hi,

Please execute the command like this

$(aws ecr get-login --region cn-northwest-1 --no-include-email `--registry-ids 937788672844`)

and try

docker pull 937788672844.dkr.ecr.cn-northwest-1.amazonaws.com.cn/c9-ide:amazonlinux-full

**Comment by iceflow** [comment]
$(aws ecr get-login --region cn-northwest-1 --no-include-email --registry-ids 937788672844)
works
The container started.

**Comment by pahud** [comment]
@iceflow thanks! make sure to `git pull` the repo. We got many [new commits](https://github.com/pahud/c9-ide/commits/master) today.
